---
- name: start bind9
  systemd:
    name: bind9
    state: started
    enabled: true

- name: stop bind9
  systemd:
    name: bind9
    state: stopped

- name: restart bind9
  systemd:
    name: bind9
    state: restarted
    daemon_reload: yes

