--- # MASTER FOR NS
- hosts: ns-all
  user: ansible
  become: true
  connection: ssh
  vars:
    whitelisted:
      - {name: 'localhost', ip: '127.0.0.1'}
      - {name: 'andynottingham2c', ip: '172.31.23.205'}
  vars_files:
    - ns/vars/bind_domain_zones.yml

  pre_tasks:
  - name: Play start
    raw: date > /home/ansible/startnsrole.log
  roles:
    - ns
  post_tasks:
  - name: Play end
    raw: date > /home/ansible/stoprole.log
