---
- hosts: ns
  user: ansible
  become: true
  connection: ssh
  vars:
    domain_zones:
      - {
	  name: "mylabserver.com",
	  networks: "172.31",
	  reverse: "31.172"
	  type: "master"}
  roles:
    - ns
