---
- name: Delete DNSSEC keys dirs if exist
  file:
    path: "{{ bind_dir }}/keys"
    state: absent

- name: Create DNSSEC keys dirs
  file:
    path: "{{ bind_dir }}/keys/{{ item.name }}"
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0755
  loop: "{{ bind_domain_zones }}"
  tags: dns

- name: Create DNSSEC keys
  command: "dnssec-keygen -r /dev/urandom -a HMAC-MD5 -b 512 -n HOST {{ item.name }}"
  args:
    chdir: "{{ bind_dir }}/keys/{{ item.name }}"
  loop: "{{ bind_domain_zones }}"
  tags: dns

- name: Get DNSSEC key value
  raw: "grep Key {{ bind_dir }}/keys/{{ item.name }}/K{{ item.name }}.*.private | awk '{print $2}'"
  register: "raw"
  loop: "{{ bind_domain_zones }}"
  tags: dns

- name: Write key secret to conf.options.keys
  template:
    src: "named.conf.options.keys.j2"
    dest: "{{ bind_dir }}/keys/named.conf.keys.{{ item.item.name }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0600
  with_items: "{{ raw.results }}"
