- name: Create zones dir
  file:
    path: "{{ bind_zone_dir }}"
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0755

- name: Create keys dir
  file:
    path: "{{ bind_zone_dir }}/keys"
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0755

- name: Create DNSSEC keys
  import_tasks: "bind_dnskeys.yml"

- name: Modify named.conf.options file
  template:
    src: named.conf.options.j2
    dest: "{{ bind_dir }}/named.conf.options"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0644
  notify: restart bind9

- name: Modify named.conf.local file
  template:
    src: named.conf.local.j2
    dest: "{{ bind_dir }}/named.conf.local"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0644
  notify: restart bind9

- name: Set BIND to IPV4
  copy:
    src: ns/files/etc/default/bind9
    dest: /etc/default/bind9
    owner: "root"
    group: "root"
  become: yes
  notify: restart bind9

- name: Allow bind to write to zones dir
  import_tasks: "bind_apparmor.yml"
