---
- name: Create forward zone file
  template:
    src: fwd_zone.j2
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    dest: "{{ bind_zone_dir }}/db.{{ item.name }}"
    mode: 0755
    validate: 'named-checkzone -d db.mylabserver.com %s'
  with_items: "{{ bind_domain_zones }}"
  tags: fwd-zone
  notify: restart bind9

- name: Create reverse zone file
  template:
    src: rev_zone.j2
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    dest: "{{ bind_zone_dir }}/db.{{ item.reverse }}"
    mode: 0755
    validate: 'named-checkzone -d db.172.31 %s'
  with_items: "{{ bind_domain_zones }}"
  tags: rev-zone
  notify: restart bind9
