- name: Install BIND9
  apt:
    pkg: ['bind9', 'bind9utils', 'bind9-doc'] 
    state: latest
  when: "ansible_os_family == 'Debian'"  
  notify: restart bind9
  
- name: Install BIND
  yum: 
    pkg: ['bind', 'bind-utils']
    state: latest
  when: "ansible_os_family == 'RedHat'"
  notify: restart named

- name: Create zones dir
  file:
    path: /etc/bind/zones
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0755

- name: Modify named.conf.options file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0755
  notify: restart bind9

- name: Modify named.conf.local file
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
  notify: restart bind9 

- name: Create forward zone file
  template:
    src: fwd_zone.j2
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    dest: /etc/bind/zones/db.mylabserver.com
    mode: 0755
  notify: restart bind9

- name: Create reverse zone file
  template:
    src: rev_zone.j2
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    dest: /etc/bind/zones/db.172.31
    mode: 0755
  notify: restart bind9
 
- name: Allow BIND9 in firewall
  command: ufw allow Bind9  
