- name: start bind9
  systemd: 
    name: bind9
    state: started

- name: stop bind9
  systemd:
    name: bind9
    state: stopped

- name: restart bind9
  systemd:
    name: bind9
    state: restarted
    daemon_reload: yes


- name: start named
  systemd:
    name: named
    state: started

- name: stop named
  systemd:
    name: named
    state: stopped

- name: restart named
  systemd:
    name: named
    state: restarted
    daemon_reload: yes


